// src/schoolMaster.ts

export interface SchoolMasterRecord {
  schoolName: string;
  campusName: string;
  adminName: string;
  adminEmail: string;
  amName: string;
  amEmail: string;
  schoolAddress: string;
  adminPhone: string;
}

export const SCHOOL_MASTER_LIST: SchoolMasterRecord[] = [
  {
    schoolName: "19/5",
    campusName: "Tứ Hiệp",
    adminName: "Chị Hạnh",
    adminEmail: "lehonghanh0210@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Ánh Trăng",
    campusName: "Yên Xá",
    adminName: "Chị Hà",
    adminEmail: "ha84.nv@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Brik English Academy",
    campusName: "Đông Hương",
    adminName: "Chị Alice",
    adminEmail: "admin@brik.edu.vn",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Em bé hạnh phúc",
    campusName: "Tây Nam Linh Đàm",
    adminName: "Chị Ngân",
    adminEmail: "happysteamykids@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Green Tree House",
    campusName: "Cơ sở 1",
    adminName: "Chị Xiêm",
    adminEmail: "greentreehouse.vp@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Hoa Mặt Trời",
    campusName: "Dịch Vọng",
    adminName: "Chị Hồng",
    adminEmail: "lehongneu93@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "IQ Linh Dam",
    campusName: "Tay Nam Linh Dam",
    adminName: "Apple",
    adminEmail: "Linhthuynguyen26@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Kids House",
    campusName: "Tây Mỗ",
    adminName: "Chị Yến",
    adminEmail: "kidshouse100@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Mầm Non Hạnh Phúc",
    campusName: "Mầm Non Hạnh Phúc",
    adminName: "Chị Thảo",
    adminEmail: "ngocthaont1010@gmail.com",
    amName: "Ginny",
    amEmail: "ginny.huynh@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Mastermind",
    campusName: "Hồ Tùng Mậu",
    adminName: "Chị Điệp",
    adminEmail: "mastermindgroup2006@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Mặt trời bé thơ",
    campusName: "Minh Khai",
    adminName: "Chị Hồng",
    adminEmail: "nguyentuyet261182@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Mat Troi Xanh Bac Ninh",
    campusName: "Bac Ninh 1",
    adminName: "Ngọc",
    adminEmail: "vuminhngoc1697@gmail.com",
    amName: "Sandra",
    amEmail: "sandra.le@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Mi Mi",
    campusName: "Resco Phạm Văn Đồng",
    adminName: "Chị Dung",
    adminEmail: "dungmama84@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "MN AMG",
    campusName: "AMG Vinhomes Gardenia",
    adminName: "Chị Phương",
    adminEmail: "anhmykindergarten@gmail.com",
    amName: "Bethany",
    amEmail: "Bethany.khuat@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "MN Bông Mai",
    campusName: "25 Tân Mai",
    adminName: "Anh Nam",
    adminEmail: "dodinhnamnd1981@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "MN Bông Mai",
    campusName: "BM GrapeSEED",
    adminName: "Anh Nam",
    adminEmail: "dodinhnamnd1981@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "MN Bông Mai",
    campusName: "STEAMe GARTEN 360 Giải Phóng",
    adminName: "Anh Nam",
    adminEmail: "dodinhnamnd1981@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "MN Hà Nội",
    campusName: "Nam Thăng Long",
    adminName: "Chị Sâm",
    adminEmail: "mntreemhanoi@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "MN Hoa Hồng",
    campusName: "Mễ Trì Thượng",
    adminName: "Chị Hồng",
    adminEmail: "bichhong3009@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "MN Làng Hạnh Phúc",
    campusName: "Nam Từ Liêm",
    adminName: "Chị Jodie",
    adminEmail: "cleveroyalkid@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "MN Những cánh diều bay",
    campusName: "FK Minh Khai",
    adminName: "Nhung Nguyễn",
    adminEmail: "nhungnguyen25389@gmail.com",
    amName: "Claire",
    amEmail: "claire.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "MN Nụ cười bé thơ 1",
    campusName: "Ngoại Giao Đoàn",
    adminName: "Chị Thủy",
    adminEmail: "gskidsmile80@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "MN Nụ cười trẻ thơ",
    campusName: "kidssmile Hoàng Quốc Việt",
    adminName: "Chị Nhung",
    adminEmail: "nhungnguyen25389@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "MN Quốc Tế Việt Ý",
    campusName: "Việt Ý An Hưng",
    adminName: "Chị Hoa",
    adminEmail: "hoanguyen19492@gmail.com",
    amName: "Sandra",
    amEmail: "sandra.le@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "MN Tài Năng Nhí",
    campusName: "TT1B Tây Nam Linh Đàm",
    adminName: "Chị Hiền",
    adminEmail: "haihiennguyen@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "MN Vườn Trí Tuệ",
    campusName: "30 Lý Nam Đế",
    adminName: "Chị Dương",
    adminEmail: "mnvuontritue88@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Nắng Xuân",
    campusName: "Đại Mỗ",
    adminName: "Chị Nga",
    adminEmail: "truongmamnonnangxuan@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Ngôi nhà cây xanh",
    campusName: "Đại Mỗ",
    adminName: "Chị Xiêm",
    adminEmail: "greentreehouse.vp@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Nguồn Sáng",
    campusName: "Mộ Lao",
    adminName: "Chị Lucy",
    adminEmail: "mns.grapeseed@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Nhà Hát Nhỏ Hà Nội",
    campusName: "NewDay Mon",
    adminName: "Chị Hoàn",
    adminEmail: "pres.newday@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Nụ cười trẻ thơ 2",
    campusName: "Ngoại Giao Đoàn",
    adminName: "Chị Thanh",
    adminEmail: "jennythuy0880@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Peakland",
    campusName: "Anh Nhật",
    adminName: "Ms. Nga",
    adminEmail: "mnanhnhat@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Peakland",
    campusName: "Peakland Preschool",
    adminName: "Ms. Giang",
    adminEmail: "peakland.school@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Peakland",
    campusName: "Song Nhue",
    adminName: "Chị Dung",
    adminEmail: "mamnonanhhoa@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Peakland",
    campusName: "Star Montessori Preschool",
    adminName: "Chị Dung",
    adminEmail: "truongmnngoisao@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Peakland",
    campusName: "Vinsmart GrapeSEED",
    adminName: "Julie",
    adminEmail: "julie.grapeseedvn@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Phuong Hong",
    campusName: "HH2E Duong Noi",
    adminName: "Chị Mai",
    adminEmail: "maint2712@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Sắc màu",
    campusName: "Ngụy Như Kon Tum",
    adminName: "Daisy",
    adminEmail: "Vanthpham317@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Sao Hà Nội",
    campusName: "CASA_60 Nguyễn Đức Cảnh",
    adminName: "Chị Tâm",
    adminEmail: "tammt84@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Sao Hà Nội",
    campusName: "HN little star Minh Khai",
    adminName: "Chị Huệ",
    adminEmail: "sunnykids.gs123@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Sao Hà Nội",
    campusName: "KIDS GARDEN_151 Nguyễn Đức Cảnh",
    adminName: "Chị Tâm",
    adminEmail: "tammt84@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Sao Hà Nội",
    campusName: "Ngoại Giao Đoàn Offline",
    adminName: "Chị Linh",
    adminEmail: "hanoi.littlestar@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Sao Hà Nội",
    campusName: "Ngoại Giao Đoàn_Online",
    adminName: "Chị Linh",
    adminEmail: "hanoi.littlestar@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Trăng Đỏ",
    campusName: "Cầu Giấy",
    adminName: "Chị Tuyết",
    adminEmail: "nguyentuyet261182@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Trung tâm Ngoại ngữ Ishine",
    campusName: "TT Ngoại ngữ Ishine",
    adminName: "Chị Hương",
    adminEmail: "giaoduc.ishine@gmail.com",
    amName: "Selena",
    amEmail: "selena.tran@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "TTNN Oscar",
    campusName: "Green Park",
    adminName: "Chị Nguyệt",
    adminEmail: "Nguyetntm174@gmail.com",
    amName: "Sandra",
    amEmail: "sandra.le@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Tuổi Thần Tiên",
    campusName: "KDT Đại Thanh",
    adminName: "Chị Nancy",
    adminEmail: "nancynguyen.grapeseed@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Tuổi Thần Tiên",
    campusName: "Văn Điển",
    adminName: "Chị Nancy",
    adminEmail: "nancynguyen.grapeseed@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Tuổi Thơ Tài Năng",
    campusName: "Tôn Đức Thắng",
    adminName: "Chị Phương",
    adminEmail: "nguyen.phuong133@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Tuổi Thơ Tài Năng",
    campusName: "Việt Hưng - CS 3",
    adminName: "Chị Phương",
    adminEmail: "nguyen.phuong133@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Viet Han",
    campusName: "KĐT Kim Văn",
    adminName: "Chị Hoài",
    adminEmail: "hoaibui76@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Việt Hàn (Kim Giang)",
    campusName: "Hoàng Đạo Thành",
    adminName: "Chị Hằng",
    adminEmail: "hangdao282@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "Việt Hàn (Kim Giang)",
    campusName: "Online",
    adminName: "Chị Hằng",
    adminEmail: "hangdao282@gmail.com",
    amName: "Emma",
    amEmail: "emma.swanepoel@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "VSK",
    campusName: "158 Võ Chí Công",
    adminName: "Chị Tuyết",
    adminEmail: "buithituyet.truonggiang@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
  {
    schoolName: "VSK Sunshine",
    campusName: "Cổ Nhuế",
    adminName: "Chị Hương",
    adminEmail: "huongvok2tn@gmail.com",
    amName: "Vivian",
    amEmail: "vivian.pham@grapeseed.com",
    schoolAddress: "",
    adminPhone: "",
  },
];
